name: learn-github-actions
on: [push]
jobs:
  do-hello-world:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Run Hello World
          uses: ./.github/actions/hello-world-action
